TemporaryDirectory /tmp/clamav
VirusEvent /etc/clamav/virusevent.d/clamav-virus-alert.sh
ExcludePath ^/dev/
ExcludePath ^/proc/
ExcludePath ^/run/
ExcludePath ^/sys/
ExcludePath ^/tmp/clamav/
ExcludePath ^/var/lib/clamav/
ExcludePath ^/var/lib/lxcfs/
ExcludePath ^/var/log/clamav/
ExcludePath ^/var/run/clamav/
OnAccessIncludePath /home/current_user/Audiobooks
OnAccessIncludePath /home/current_user/Desktop
OnAccessIncludePath /home/current_user/Documents
OnAccessIncludePath /home/current_user/Downloads
OnAccessIncludePath /home/current_user/Music
OnAccessIncludePath /home/current_user/Pictures
OnAccessIncludePath /home/current_user/Public
OnAccessIncludePath /home/current_user/Templates
OnAccessIncludePath /home/current_user/Videos
OnAccessIncludePath /home/current_user/bin
OnAccessIncludePath /tmp
OnAccessIncludePath /usr/local/bin
OnAccessIncludePath /usr/local/sbin
OnAccessIncludePath /var/tmp
OnAccessExcludePath /tmp/clamav
OnAccessExcludeUname clamav
OnAccessExtraScanning yes
OnAccessPrevention yes
