#!/usr/bin/bash

# Discussion, issues and change requests at:
#   https://github.com/xmready/setup-debian
#
# Purpose:
#   A script to update, upgrade, and full-upgrade using apt
#
# Usage:
#   curl -fL https://raw.githubusercontent.com/xmready/setup-debian/main/scripts/command-desktop-autoupgrade.sh | bash -

get_latest_release() {
  curl --fail --silent "https://api.github.com/repos/$1/releases/latest" |
  grep tag_name |
  sed -E 's/.*"([^"]+)".*/\1/'
}

nvm_version="$(get_latest_release nvm-sh/nvm)" || { echo "Error: failed to get nvm version"; exit 1; }
nvm_url="https://raw.githubusercontent.com/nvm-sh/nvm/${nvm_version}/install.sh"

echo -e "\n$(tput setaf 3)upgrading apt\n$(tput sgr0)" \
&& sudo apt-get update \
&& sudo apt-get upgrade -y \
&& sudo apt-get full-upgrade -y \
&& echo -e "\n$(tput setaf 2)apt upgraded\n$(tput sgr0)" \
&& sleep 3 \
&& echo -e "\n$(tput setaf 3)upgrading rclone\n$(tput sgr0)" \
&& sudo rclone selfupdate --package deb \
&& echo -e "\n$(tput setaf 2)rclone upgraded\n$(tput sgr0)" \
&& sleep 3 \
&& echo -e "\n$(tput setaf 3)cleaning apt\n$(tput sgr0)" \
&& sudo apt-get -y autoremove \
&& sudo apt-get -y autoclean \
&& echo -e "\n$(tput setaf 2)apt cleaned\n$(tput sgr0)" \
&& sleep 3 \
&& echo -e "\n$(tput setaf 3)upgrading flatpaks\n$(tput sgr0)" \
&& flatpak update -y \
&& echo -e "\n$(tput setaf 2)flatpaks upgraded\n$(tput sgr0)" \
&& sleep 3 \
&& echo -e "\n$(tput setaf 3)upgrading nvm\n$(tput sgr0)" \
&& curl -fL "$nvm_url" | bash - \
&& echo -e "\n$(tput setaf 2)nvm upgraded\n$(tput sgr0)"
